import customtkinter as ctk
from .settings import app
from .functions import *

frame = ctk.CTkFrame(app)
button = ctk.CTkButton(frame, text = 'Open Image', command = lambda: upload_image(slider_bright, entry_width, entry_height))
frame.pack(pady = 20)
button.pack(pady = 5)
button_download = ctk.CTkButton(frame, text = 'Download', command = lambda: save_image(entry_width, entry_height))
button_download.pack(pady = 5)
button_rotate = ctk.CTkButton(app, text = 'Rotate', command = rotate_image)
button_rotate.place(x = 650, y = 20)
button_bw = ctk.CTkButton(app, text = 'B&W', command = bw_image)
button_bw.place(x = 650, y = 60)
button_blur = ctk.CTkButton(app, text = 'Blur', command = blur_image)
button_blur.place(x = 650, y = 100)
label_bright = ctk.CTkLabel(app, text = 'Brightness')
label_bright.place(x = 12, y = 8)
slider_bright = ctk.CTkSlider(app, from_ = 0.9, to = 1.1, command = brightness_image)
slider_bright.place(x = 5, y = 40)
label_contrast = ctk.CTkLabel(app, text = 'Contrast')
label_contrast.place(x = 12, y = 63)
slider_bright = ctk.CTkSlider(app, from_ = 0, to = 2, command = contrast_image)
slider_bright.place(x = 5, y = 95)
button_undo = ctk.CTkButton(app, text = 'Undo changes', command = undo_changes)
button_undo.place(x = 620, y = 650)
button_crop = ctk.CTkButton(app, text = 'Crop', command = crop)
button_crop.place(x = 650, y = 140)
frame_size = ctk.CTkFrame(app)
frame_size.place(x = 500, y = 15)
label_width = ctk.CTkLabel(frame_size, text = 'Width')
label_width.pack()
entry_width = ctk.CTkEntry(frame_size, 100)
entry_width.pack()
label_height = ctk.CTkLabel(frame_size, text = 'Height')
label_height.pack()
entry_height = ctk.CTkEntry(frame_size, 100)
entry_height.pack()
button_text = ctk.CTkButton(app, text = 'Add Text', command = lambda: label.bind('<Button-1>', open_text_modal))
button_text.place(x = 650, y = 180)
button_watermark = ctk.CTkButton(app, text = 'Remove Watermark\n(beta)', command = watermark_remove)
button_watermark.place(x = 650, y = 220)