from .settings import app, ctk
from .functions import *

frame = ctk.CTkFrame(app)
button = ctk.CTkButton(frame, text = 'Open Image', command = lambda: upload_image())
frame.pack(pady = 20)
button.pack(pady = 5)
button_open_drive = ctk.CTkButton(frame, text = 'Open From Drive', command = lambda: upload_image_from_drive())
button_open_drive.pack(pady = 5)
button_download = ctk.CTkButton(frame, text = 'Download', command = lambda: save_image())
button_download.pack(pady = 5)
button_rotate = ctk.CTkButton(app, text = 'Rotate', command = rotate_image)
button_rotate.place(x = 650, y = 20)
button_bw = ctk.CTkButton(app, text = 'B&W', command = bw_image)
button_bw.place(x = 650, y = 60)
button_blur = ctk.CTkButton(app, text = 'Blur', command = blur_image)
button_blur.place(x = 650, y = 100)
label_bright = ctk.CTkLabel(app, text = 'Brightness')
label_bright.place(x = 12, y = 8)
mutable_objects['slider_bright'] = ctk.CTkSlider(app, from_ = 0.9, to = 1.1, command = brightness_image)
mutable_objects['slider_bright'].place(x = 5, y = 40)
label_contrast = ctk.CTkLabel(app, text = 'Contrast')
label_contrast.place(x = 12, y = 63)
mutable_objects['slider_contrast'] = ctk.CTkSlider(app, from_ = 0, to = 2, command = contrast_image)
mutable_objects['slider_contrast'].place(x = 5, y = 95)
button_undo = ctk.CTkButton(app, width = 80, text = 'Undo', command = undo_changes)
button_undo.place(x = 620, y = 650)
button_redo = ctk.CTkButton(app, width = 80, text = 'Redo', command = redo_changes)
button_redo.place(x = 710, y = 650)
button_crop = ctk.CTkButton(app, text = 'Crop', command = crop)
button_crop.place(x = 650, y = 140)
frame_size = ctk.CTkFrame(app)
frame_size.place(x = 500, y = 15)
label_width = ctk.CTkLabel(frame_size, text = 'Width')
label_width.pack()
mutable_objects['entry_width'] = ctk.CTkEntry(frame_size, 100)
mutable_objects['entry_width'].pack()
label_height = ctk.CTkLabel(frame_size, text = 'Height')
label_height.pack()
mutable_objects['entry_height'] = ctk.CTkEntry(frame_size, 100)
mutable_objects['entry_height'].pack()
button_text = ctk.CTkButton(app, text = 'Add Text', command = lambda: label.bind('<Button-1>', open_text_modal))
button_text.place(x = 650, y = 180)
button_watermark = ctk.CTkButton(app, text = 'Remove Watermark\n(beta)', command = watermark_remove)
button_watermark.place(x = 650, y = 220)
button_background = ctk.CTkButton(app, text = 'Remove Background', command = background_remove)
button_background.place(x = 650, y = 260)